meta_product_name: "BethCodes"
meta_title: "BethCodes - a trustworthy full stack developer for your web development needs"
meta_description: "Reliable with a high attention to detail, Beth is an ambitious web developer always driven to grow and improve. View her full portfolio here."
meta_image: "BethCodes_meta.png"
